---
title: "MRE Tests"
author: "Davide Lorino"
date: "2023-06-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries and Data

```{r}
library(mre)
library(bnlearn)
library(dplyr)
library(tidyr)
library(ggplot2)
library(plotly)
library(causaldata)
data("Seatbelts")
data("asia")
data("insurance")
data("avocado")
```

# Insurance 

## Likelihood Ratio

```{r}
insurance_accident_severe <- mre::mre_hierarchical_beam_search(
  x = insurance %>% 
    dplyr::select(-Theft, -Age) %>%
    mutate(BreathesOxygen = "Yes"),
  target_variable = "GoodStudent",
  target_value = "False",
  metric = "likelihood ratio"
) 



g <- insurance_accident_severe %>%
  arrange(desc(gbf_score)) %>%
  head(5) %>%
          ggplot(aes(x = `hypothesis`, y = `gbf_score`)) +
              geom_bar(position="stack", stat="identity") +
              #theme_classic() +
              theme(
                panel.background = element_rect(fill = "#35353B", color = "#35353B"),
                plot.background = element_rect(fill = "#35353B", color = "#35353B"),
                axis.text.x = element_text(color = "white"),
                axis.text.y = element_text(color = "white"),
                axis.title.y = element_text(color = "white"),
                axis.title.x = element_text(color = "white"),
                axis.ticks.x = element_line(color = "white"),
                legend.text = element_text(color = "white"),
                legend.background = element_rect(fill = "#35353B", color = "#35353B"),
                legend.title = element_blank()
              ) +
              coord_flip() +
              labs(x="",y="GBF Score")

ggplotly(g) %>%
   config(displayModeBar = F)
```

# Avovado Sales

## Posterior Odds

```{r}

avocado %>%
  mutate(PriceChange = AveragePrice - lag(AveragePrice)) %>%
  mutate(VolumePurchasedByPeopleWhoBreatheOxygen = TotalVolume) %>%
  mutate(VolumeChange = TotalVolume - lag(TotalVolume)) %>%
  select(PriceChange, VolumeChange, TotalVolume) %>%
  mutate(PriceChangeCat = 
           case_when(PriceChange > 0 ~ "Up", 
                     TRUE ~ "Down"
                     ),
         VolumeChangeCat = 
           case_when(VolumeChange > 0 ~ "Up",
                     TRUE ~ "Down"
                     ),
         CustomersBreatheOxygen = "Yes"
           ) %>%
  filter(!is.na(VolumeChange) & !is.na(PriceChange)) %>%
  select(PriceChangeCat, VolumeChangeCat, CustomersBreatheOxygen) %>%
  mre::mre_hierarchical_beam_search(target_variable = "VolumeChangeCat", target_value = "Down")

```

## Likelihood Ratio

```{r}
avocado %>%
  mutate(PriceChange = AveragePrice - lag(AveragePrice)) %>%
  mutate(VolumePurchasedByPeopleWhoBreatheOxygen = TotalVolume) %>%
  mutate(VolumeChange = TotalVolume - lag(TotalVolume)) %>%
  select(PriceChange, VolumeChange, TotalVolume) %>%
  mutate(PriceChangeCat = 
           case_when(PriceChange > 0 ~ "Up", 
                     TRUE ~ "Down"
                     ),
         VolumeChangeCat = 
           case_when(VolumeChange > 0 ~ "Up",
                     TRUE ~ "Down"
                     ),
         CustomersEnjoyPizza = factor(
           sample(
             c("Yes", "No"), 
             nrow(avocado), 
             replace = TRUE, 
             prob = c(0.99, 0.01)
             )
            )
           ) %>%
  filter(!is.na(VolumeChange) & !is.na(PriceChange)) %>%
  select(PriceChangeCat, VolumeChangeCat, CustomersEnjoyPizza) %>%
  mre::mre_hierarchical_beam_search(
    target_variable = "VolumeChangeCat", 
    target_value = "Down", 
    metric = "posterior odds"
    ) #%>%



```


